[profile.default]
src = "contracts"
out = "out"
libs = ['node_modules', 'lib']
solc = "0.8.17"
viaIR = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
