import {
    AccessTokenG7Args,
    AvatarBoundV1Args,
    CamelotDistributorArgs,
    ItemBoundArgs,
    LevelsBoundV1Args,
    PaymentRouterNativeG7Args,
    RewardsNativeG7Args,
    StakerArgs,
} from '@constants/constructor-args';
import {
    CONTRACT_TYPE,
    CONTRACT_UPGRADABLE_NAME,
    CONTRACT_UPGRADABLE_FILE_NAME,
    CONTRACT_FILE_NAME,
    CONTRACT_NAME,
} from '@constants/contract';
import { TENANT } from '@constants/tenant';

import { DeploymentContract } from '../../types/deployment-type';
import { NETWORK_TYPE, NetworkName } from '../network';

const chain = NetworkName.Game7;
const networkType = NETWORK_TYPE.MAINNET;

export const G7_MAINNET_CONTRACTS: DeploymentContract[] = [
    {
        contractFileName: CONTRACT_UPGRADABLE_FILE_NAME.Avatars,
        type: CONTRACT_TYPE.Avatars,
        name: CONTRACT_UPGRADABLE_NAME.Avatars,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: true,
        dependencies: [CONTRACT_UPGRADABLE_NAME.Items, CONTRACT_UPGRADABLE_NAME.Levels],
        functionCalls: [],
        args: AvatarBoundV1Args.MAINNET,
    },
    {
        contractFileName: CONTRACT_UPGRADABLE_FILE_NAME.Levels,
        type: CONTRACT_TYPE.Levels,
        name: CONTRACT_UPGRADABLE_NAME.Levels,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: true,
        dependencies: [CONTRACT_UPGRADABLE_NAME.Items, CONTRACT_UPGRADABLE_NAME.Avatars],
        args: LevelsBoundV1Args.MAINNET,
    },
    {
        contractFileName: CONTRACT_UPGRADABLE_FILE_NAME.ERC1155RoyaltiesSoulbound,
        type: CONTRACT_TYPE.Items,
        name: CONTRACT_UPGRADABLE_NAME.Items,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: true,
        dependencies: [],
        functionCalls: [
            {
                contractName: CONTRACT_UPGRADABLE_NAME.Items,
                functionName: 'grantRole',
                args: ['MINTER_ROLE', `CONTRACT_${CONTRACT_UPGRADABLE_NAME.Avatars}`],
            },
            {
                contractName: CONTRACT_UPGRADABLE_NAME.Items,
                functionName: 'grantRole',
                args: ['MINTER_ROLE', `CONTRACT_${CONTRACT_UPGRADABLE_NAME.Levels}`],
            },
        ],
        args: ItemBoundArgs.MAINNET,
    },
    {
        contractFileName: CONTRACT_FILE_NAME.AccessToken,
        type: CONTRACT_TYPE.RewardAccessToken,
        name: CONTRACT_NAME.RewardAccessTokenG7,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: false,
        dependencies: [],
        functionCalls: [
            {
                contractName: CONTRACT_NAME.RewardAccessTokenG7,
                functionName: 'initialize',
                args: [
                    'AccessToken',
                    'AT',
                    'NO_VALUE',
                    'NO_VALUE',
                    'DEPLOYER_WALLET',
                    /* this should be the minterContract -> RewardsNativeG7 */ 'MINTER_ROLE',
                ],
            },
        ],
        args: AccessTokenG7Args.MAINNET,
    },
    {
        contractFileName: CONTRACT_FILE_NAME.RewardsNative,
        type: CONTRACT_TYPE.Rewards,
        name: CONTRACT_NAME.RewardsNativeG7,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: false,
        dependencies: [CONTRACT_NAME.RewardAccessTokenG7],
        functionCalls: [],
        args: RewardsNativeG7Args.MAINNET,
    },
    {
        contractFileName: CONTRACT_FILE_NAME.PaymentRouterNative,
        type: CONTRACT_TYPE.PaymentRouter,
        name: CONTRACT_NAME.PaymentRouterNativeG7,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: false,
        dependencies: [],
        functionCalls: [],
        args: PaymentRouterNativeG7Args.MAINNET,
    },
    {
        contractFileName: CONTRACT_FILE_NAME.Distributor,
        type: CONTRACT_TYPE.CamelotDistributor,
        name: CONTRACT_NAME.Distributor,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: false,
        dependencies: [],
        functionCalls: [],
        args: CamelotDistributorArgs.MAINNET,
    },
    {
        contractFileName: CONTRACT_UPGRADABLE_FILE_NAME.ERC1155Soulbound,
        type: CONTRACT_TYPE.Badges,
        name: CONTRACT_UPGRADABLE_NAME.Badges,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: true,
        dependencies: [],
        functionCalls: [],
        args: ItemBoundArgs.MAINNET,
    },
    {
        contractFileName: CONTRACT_FILE_NAME.PositionMetadata,
        type: CONTRACT_TYPE.Metadata,
        name: CONTRACT_NAME.PositionMetadata,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: false,
        dependencies: [],
        functionCalls: [],
        args: {},
    },
    {
        contractFileName: CONTRACT_FILE_NAME.Staker,
        type: CONTRACT_TYPE.Staker,
        name: CONTRACT_NAME.Staker,
        chain,
        networkType,
        tenants: [TENANT.Game7],
        verify: true,
        upgradable: false,
        dependencies: [CONTRACT_NAME.PositionMetadata],
        functionCalls: [],
        args: StakerArgs.MAINNET,
    },
];
