name: Smart Contract CI

on:
  pull_request:
    paths:
      - 'contracts/**'

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  FOUNDRY_PROFILE: ci

jobs:
#  TODO: Uncomment this section to enable security audit when all the slither warnings are fixed
#  security_audit:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18.x'
#          registry-url: 'https://registry.npmjs.org'
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.x'
#
#      - name: Install Slither
#        run: python -m pip install slither-analyzer
#
#      # Run Slither on all contracts except dependencies
#
#      - name: Run Slither
#        run: slither . --exclude-dependencies --include contracts/facets/Inventory.sol, contracts/Inventory.sol

#  check_foundry_tests:
#    strategy:
#      matrix:
#        solidity: ['0.8.17']
#        hardhat: ['^2.12.7']
#        node: ['18.x']
#      fail-fast: true
#
#    name: Foundry project
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: recursive
#
#      - name: Install Foundry
#        uses: foundry-rs/foundry-toolchain@v1
#        with:
#          version: nightly
#
#      - name: Run Forge build
#        run: |
#          forge --version
#          forge build --sizes
#        id: build
#
#      - name: Run Forge tests
#        run: |
#          forge test -vvv
#        id: test

  code_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run Hardhat tests
        run: npx hardhat --config hardhat.config.ts test

#      - name: Enforce Coverage
#        run: npx istanbul check-coverage --statements 36.5 --branches 17.5 --functions 40 --lines 30

